### PR TITLE
[WIP] Refactor CloudValue, Caching, PersistedCloudFlow

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
This PR introduces yet another set of comprehensive refactorings in the core library. It is part of the greater effort to migrate core runtime functionality to the MBrace.Runtime.Core library. The centerpiece of this refactoring is the transformation of `CloudValue<'T>` into an ADT. The CloudValue creator method now has the following type signature:
```fsharp
CloudValue.New : value:'T * ?storageLevel:StorageLevel -> Local<ICloudValue<'T>>
```
The optional parameter is an enumeration indicating the way this value is going to be cached. Some possible values include `StorageLevel.Memory`, `StorageLevel.MemorySerialized` and `StorageLevel.Disk`. Combinations such as `StorageLevel.MemoryAndDisk` or `MemoryAndDiskSerialized` are also possible. This has been essentially lifted from the Spark [StorageLevel](https://spark.apache.org/docs/latest/programming-guide.html#rdd-persistence) enumeration. The actual implementation of these storage levels, if at all supported, are up to the runtime. `MBrace.Runtime.Core` comes with a base implementation that uses file storage, System.Runtime.Caching and FsPickler object hashing functionality. For MBrace.Azure it might make sense to have a CloudValue implementation that uses the Azure cache.

The CloudFlow library makes use of the new CloudValue primitive to extend the persisting API. The persist method has type signature
```fsharp
CloudFlow.persist : StorageLevel -> CloudFlow<'T> -> Cloud<PersistedCloudFlow<'T>>
```
whereas
```fsharp
CloudFlow.cache : CloudFlow<'T> -> Cloud<PersistedCloudFlow<'T>>
```
is just calling the above with `StorageLevel.Memory`. This means that CloudFlow now supports in-memory caching alone. It should be noted however that CloudFlow will still *not* support recomputation in case of a lost worker node, due to fundamental restrictions coming with the CloudFlow abstraction. I am confident however that alternative, LINQ-style libraries can also be developed on top of the current MBrace.Core that support this.

Another important change introduced with this PR is the movement of a significant part of the Store API from `Local<_>` to `Async<_>`. For instance, in the master branch `ICloudAtom<'T>` has (roughly) the following signature:
```fsharp
type ICloudAtom<'T> =
    abstract Value : Local<'T>
    abstract Update : ('T -> 'T) -> Local<'T>
```
The trouble with this approach is that the API remains essentially inaccessible unless consumed within the context of a cloud workflow. This is because unlike `Async`, `Local/Cloud` is really a reader monad, which depends on an environment in order to run properly. This PR disposes of this purist approach for a more pragmatic solution:
```fsharp
type ICloudAtom<'T> =
    abstract Value : 'T
    abstract Update : ('T -> 'T) -> 'T
    abstract GetValueAsync : unit -> Async<'T>
    abstract UpdateAsync : ('T -> 'T) -> Async<'T>
```
What this means is that store primitives are now being forced to encapsulate all connection information, rather than importing it from the context. This permits freer experimentation on the data primitives, particularly from fsi.

This does *not* mean that we are deprecating `Local<'T>`. Local still has an important role to play in the programming model, as can be evidenced the type signature:
```fsharp
CloudAtom.New : 'T -> Local<ICloudAtom<'T>> 
```
This signifies a computation that is local yet requires dependency injection in order to materialise the store primitive. MBrace computation expressions now contain `Bind` and `ReturnFrom` overloads that permit seamless composition with async workflows:
```fsharp
local {
    let! atom = CloudAtom.New 17
    let! i = atom.Update (fun i -> i + 25)
    return i
}
```

### CODE REVIEW

**Comment by isaacabraham** [comment]
this reads really well. great stuff. Obviously I'm keen to see a working version of ```CloudFlow``` that supports in-memory caching, as well as in the future an Azure-friendly version that uses the in-memory worker cache - but one step at a time :-)

**Comment by eiriktsarpalis** [comment]
@isaacabraham for now, you can see it in action using [MBrace.Thespian](https://github.com/mbraceproject/MBrace.Core/blob/caching-refactoring/samples/MBrace.Thespian/test.fsx) in your local machine. The client API is pretty much the same MBrace.Azure.

**Comment by isaacabraham** [comment]
Nice. What does Thespian use for messaging and job tracking?

**Comment by eiriktsarpalis** [comment]
[Thespian](http://nessos.github.io/Thespian/) :)

It's essentially the actor framework we were using for the old MBrace.

**Comment by eiriktsarpalis** [comment]
Basically it assures "fault tolerance" by keeping all cluster book-keeping in the client process (i.e. fsi). Workers can be killed and respawned without affecting computation. Obviously, this is only meant for testing.

**Pull request merged**
