### PR TITLE
With removal

### PR DESCRIPTION
**Pull request by dsyme**
Using "with" in "type C = repr with... " is not really idiomatic

### CODE REVIEW

**Comment by eiriktsarpalis** [comment]
Something seems to be wrong with the build.

**Comment by dsyme** [comment]
AppVeyor is OK. All Travis builds are having problems - I think something to do with ExtensionAttribute. Am trialling a fix for that in #147

**Comment by dsyme** [comment]
Will merge this since AppVeyor is ok

**Comment by palladin** [comment]
It seems that the C# mono compiler can't resolve extension method ToFSharpFunc?

**Pull request merged**
