### PR TITLE
[WIP] basic graph proccessing

### PR DESCRIPTION
**Pull request by AviAvni**
After playing with GraphX I thought this concept can be great
Also want to work on more algorithms and functions

### CODE REVIEW

**Comment by isaacabraham** [comment]
cc:@bruinbrown weren't you trying a graph engine on MBrace?

**Comment by isaacabraham** [comment]
@AviAvni thanks a lot for this! not sure what my time will be like in the coming days to review this, by graph processing would be cool. I'll wondering if this will grow and if it should be in it's own package e.g. MBrace.Graph.

Thoughts?

**Comment by AviAvni** [comment]
@isaacabraham  I'm tring to keep it simple as possible and for now it base on mbrace.flow so and don't want to mix
So for me it doesn't matter
I want it to be as close as possible to Spark Graphx so I will add PageRank triangle count and so on
Just wanted first review so I'll be sure I'm in the right direction and the community is interested

**Comment by AviAvni** [comment]
@isaacabraham @eiriktsarpalis please review also implemented pregel maybe need some help with CloudFlow.persis

**Comment by AviAvni** [comment]
added PageRank algo

**Comment by eiriktsarpalis** [comment]
OK, I took the time to review the code. It all looks very interesting, however I do have concerns related to how computation is orchestrated in the distributed scope.

* The `GetAttr` implementation is a distributed computation based on CloudFlow that will eagerly utilize all cluster resources to locate the vertex. The fact that it is being called per vertex per edge in a potentially large graph makes me worry that this will not scale well.
* CloudFlow should not be used for generating `Cloud<_>` values. This is because it results in a distributed flow computation that only serves to allocate a lot of closures. Passing those subsequently to `Cloud.Parallel` means that they will be executed in a non-optimized way (i.e. one job scheduled per vertex).
* Minor issue, but the `use!` on `CloudDictionary` should be replaced with `let!`, since it will cause it to be disposed once aggregation is complete.

A good approach here would be to replace the expensive `GetAttr` implementation with using one of the `CloudFlow.join*` combinators. This would ensure that vertex and edge data are joined in a way that does not entail scheduling overhead. However it does seem to me that a better long-term approach would be to introduce dedicated data structures for more efficient graph processing.

**Comment by AviAvni** [comment]
@eiriktsarpalis thanks for you review
I removed the GetAttr function and instead use CloudDictionary
Now cloud flow don't generate cloud value and the api more simple
And I replaced the use! with let!(how I didn't notice that the dictionary is disposed when I run the samples?)
I tried the join you mention but I think we need to write other join because here every Edge need to be joined to 2 Nodes what do you think now?

**Comment by AviAvni** [comment]
And I improved the performance of Pregel by not creating every time new graph

**Comment by eiriktsarpalis** [comment]
This looks much better, however I'm still not convinced that the CloudDictionary/CloudFlow combination is ideal w.r.t. performance. The main thing is that CloudFlow pipelines are optimized for use with pure computations inside their lambdas. On the other hand, updating and entry in a CloudDictionary typically runs an update operation against a database (table storage with optimistic updates in the case of MBrace.Azure).

> I tried the join you mention but I think we need to write other join because here every Edge need to be joined to 2 Nodes

Most join operations in CloudFlow are implemented on top of a [`foldBy2`](https://github.com/mbraceproject/MBrace.Core/blob/master/src/MBrace.Flow/Consumers/Fold.fs#L172) primitive. Can you investigate whether graph workflows can be run on top of a variation of `foldBy2`? The main benefit of this approach is that elements are shuffled by key before the computation takes place.

> And I replaced the use! with let!(how I didn't notice that the dictionary is disposed when I run the samples?)

It's probably because you're running it on MBrace.Thespian. Thespian is a testing-only implementation where many features have not been implemented. MBrace.Azure offers a better way of appreciating implementations and the performance impact of distribution.

**Comment by AviAvni** [comment]
@eiriktsarpalis Hi thanks for your comment
Now I removed all CloudDictionary and use join
I tried to make it one join but its little hard do you have direction for me?

**Comment by eiriktsarpalis** [comment]
@AviAvni I took a look at the latest changes. `CloudFlow.Persist`is a combinator that forces computation by storing all data in partitions across the cluster. This is done for running multiple subsequent queries on the dataset efficiently. It seems that persisted values here are only consumed once, so I think it's not appropriate to use.

Overall, good progress. I would be interested to know whether the two joins can be merged into a single operation to minimize the distribution overhead. Did you take a look at `foldBy2`? Perhaps it or a generalization of that combinator could be used here.

**Comment by AviAvni** [comment]
@eiriktsarpalis thanks for the comment
I'll check again the difference without persist
I looked at foldby2 and tried to implement new one every day 
but still don't get something work maybe we can do Skype meeting give me some directions?

**Pull request closed without merging**
