### PR TITLE
Runtime core refactoring

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
This PR introduces significant rewrites to the `MBrace.Runtime.Core` library. This is part of an ongoing effort to provide a common foundation for MBrace runtimes and facilitate the porting of MBrace functionality to many cloud services. The goal is to provide a common semantics for execution of MBrace programs w.r.t to parallelism and serialization, in a way that it is hidden away from implementers of runtimes. In essence, you only need to provide a store implementation, job scheduling and worker management.

The MBrace sample runtime implementation (renamed to MBrace.Thespian) is now a feature-complete implementation in just above 1000 LOC.

The next goal is to refactor MBrace.Azure so that it makes use of MBrace.Runtime.Core. This should significantly reduce implementation size and complexity and will allow us to focus on other cloud services as well.

### CODE REVIEW

**Comment by dsyme** [comment]
Why "Thespian"? :)

**Comment by eiriktsarpalis** [comment]
@dsyme it's an implementation of the MBrace runtime over the [Nessos.Thespian](http://nessos.github.io/Thespian/) actor library.

**Comment by dsyme** [comment]
OK :)

**Comment by palladin** [comment]
This is Sparta :)

**Pull request merged**
