### PR TITLE
[WIP] MBrace.Core store components extension method refactoring

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
This PR addresses issue #115. It removes Bind and ReturnFrom methods on Async workflows by default. Store primitive interfaces are still implemented using Async, however these are explicitly named using the 'Async' Suffix. 'Local' versions for the store primitives are defined using extension methods, to replace the static methods that are being used now. /cc @dsyme

### CODE REVIEW

**Comment by eiriktsarpalis** [comment]
The refactoring is complete. I must say I'm pleased with the result. Overall, the changes look as follows:
overall storage primitive interface use async methods explicitly named so:
```fsharp
type CloudQueue<'T> =
     abstract DequeueAsync : unit -> Async<'T>
```
which are augmented with extension methods:
```fsharp
type CloudQueue<'T> with
     member Dequeue : unit -> Local<'T>
```
I was wondering whether we should also add synchronous extension methods. Possibly
```fsharp
type CloudQueue<'T> with
    member DequeueLocal : unit -> Local<'T>
    member Dequeue : unit -> 'T
```
Thoughts?

**Comment by dsyme** [comment]
This looks good.  I thought you'd ask about the synchronous methods :)  I think just leave it like you have it.  This is a cloud monadic programming framework and it's reasonable for operations to be in the monad by default including naming.

**Comment by eiriktsarpalis** [comment]
Here's another thought: MBrace workflows can be asynchronous, however this may not be evident to casual users of the library. At the same time, I feel that asynchrony in the context of distributed big compute/big data analytics is not nearly as critical as in the context of other applications like web services. So my proposal is the following: completely remove the Local<> instance methods from the store primitives and only leave asynchronous and synchronous implementations, the latter being derived from the former using extension methods. In this way, we achieve two things:
  1. Ease of use when evaluating from the client side.
  2. Familiarity for the average .NET programmer, since most libraries come with dual sync/async APIs.

In cases where asynchrony is essential, we can force the user to go down the explicit way:
```fsharp
let! value = queue.DequeueAsync() |> Cloud.OfAsync
```
But I think that this is nice, since it clearly communicates that this is a non-blocking call. The same is not true when calling `queue.Dequeue() : Local<'T>`. In most cases, calling the synchronous methods inside cloud workflows is good enough, and it is also more friendly when pattern matching:
```fsharp
cloud { match queue.Dequeue() with .... }
```
What do you think?

**Comment by dsyme** [comment]
Yes, this is a possibility and it would certainly make I/O in the framework simpler.

> In cases where asynchrony is essential, we can force the user to go down the explicit way:
>   let! value = queue.DequeueAsync() |> Cloud.OfAsync

Could you describe the practical effect of adding the asynchrony here?  I presume it adds a cancellation point?  What else?   And how concerned are we that moving to sync-io-by-default might reduce the cancellability of cloud computations?

**Comment by eiriktsarpalis** [comment]
@dsyme Whether we used a `Dequeue() : Local<'T>` or DequeueAsync with
Cloud.OfAsync the effect wrt asynchrony is equivalent. The only difference
I suppose is that the latter is better at communicating this fact to the
user.

Indeed sync calls diminish cancellability but I'm sure that a seasoned user
of Async already understands that.

**Comment by dsyme** [comment]
> Indeed sync calls diminish cancellability but I'm sure that a seasoned user of Async already understands that.

Some thoughts.... If I understand correctly, this change would effectively make sync I/O the default for MBrace programming - for example ``CloudFile.ReadAllLines`` would now be synchronous, and this is the one people will use by default.  There would now be relatively few ``let!`` or ``do!`` in ``cloud { ... }`` code unless the programmer manually introduces asynchrony.  (as one side effect, the need for the ``CloudFlow.mapLocal`` would also be greatly reduced)

For example there are 28 uses of ``let!`` and 17 uses of ``do!`` in the starter pack, nearly all related to I/O or logging.  (Q: would ``Cloud.Logf`` also be synchronous with an async version?)

Certainly programming will become less monadic and more simple (which probably trumps everything else). There would also be paths to put more cancellability back into code manually.

**Comment by eiriktsarpalis** [comment]
`CloudFile.ReadAllLines` is a static method that relies on the `ICloudFileStore` dependency, so it must remain of type Local<>. Therefore, it can also be asynchronous, as it is now. The same is true for `Cloud.Logf` because it needs to resolve the `ICloudLogger` dependency, which is not necessarily asynchronous.

The changes here only affect materialized instances of storage primitives. Since they already encapsulate all needed dependencies, it is not necessary for their methods to be of type Local<>.

**Comment by dsyme** [comment]
Ah yes ,sorry, let's take ``CloudQueue.Enqueue`` as the example.

**Comment by eiriktsarpalis** [comment]
So `CloudQueue.Dequeue` is now an instance method. Currently you have `queue.DequeueAsync : unit -> Async<'T>` and `queue.Deqeue : unit -> Local<'T>`, both of which are asynchronous and largely equivalent. The catch here is that it is straightforward to obtain the latter from the former but not the other way around. Under the proposed change the latter would have been `queue.Dequeue: unit -> 'T`. The nice thing about this API is that to the novice .NET user the former is obviously asynchronous while the latter is obviously blocking. This might not be evident when having a method returning Local<>.

**Comment by dsyme** [comment]
Hmmm... 

First I'm assuming MBrace programmers aren't particularly comfortable with mixing ``async`` and ```cloud``.   Let's assume they are comfortable just doing ``cloud` and little else, and probably have little idea about how the two relate.

For these programmers (who I assume are the norm), with the above change some I/O operations would return ``T``, some return ``Async<T>`` and some return ``Local<T>``. It feels inconsistent and it will take programmers out of their comfort zone.  It feels like we just have to make ``Async`` disappear from routine MBrace programming (since the others can't be eliminated).  We are almost there apart from these instance members which are dragging us back towards ``Async``.

Likewise, this kind of programmer will also find it strange that they use ``let!`` for some cloud I/O operations, and ``let`` for others (the point about encapsulation is subtle and won't be apparent to the beginner).    

I'm still wondering, why not just have ``queue.Deqeue : unit -> Local<'T> `` and nothing else?  From the programmer's perspective this gives the very simple story that all I/O operations are cloud monadic.  I understand the point about encapsulation but I'd say the priority has to be to keep things very simple and regular for the programmer: *all cloud I/O is cloud-monadic*.

The alternative is to make all cloud I/O synchronous, but then we'd to do it across the board to *all* I/O primitives, which means encapsulating files once again, which would be a shame.

Cheers
don

**Comment by eiriktsarpalis** [comment]
> I understand the point about encapsulation but I'd say the priority has to be to keep things very simple and regular for the programmer: all cloud I/O is cloud-monadic.

This is in fact a principle that earlier versions of MBrace followed. In practice however this resulted in complaints from users like "Why can't I dequeue straight from fsi?" or "Why can't I read a CloudValue in CloudFlow.map?". Answers like "you should evalute cloud workflows using cluster.RunLocally" or "you need to recover the ResourceRegistry of the running cloud process and pass it to Cloud.RunSynchronously" add to the confusion. Even worse, the API is bloated with countermeasure implementations like `CloudFlow.mapLocal` which may appear asynchronous when in fact they are not.

In part we were influenced to abandon this principle by the Spark API, in which almost every public method is synchronous.

**Comment by palladin** [comment]
In practise, for some primitives it is very convenient to have Async<T>/'T methods especially for primitives that offer caching in a non-monadic context etc.

**Comment by eiriktsarpalis** [comment]
Let me see if I can encode my thoughts in a table:

| Type         	| Intended Purpose                                    	| Distributed 	| Has Dependencies 	| Asynchronous       	|
|--------------	|--------------------------------------------	|-------------	|----------------------	|--------------------	|
| `Cloud<'T>`  	| Distributed computation                      	| Perhaps | Yes                  	| Perhaps, implicit  	|
| `Local<'T>`  	| Local computation /w Dependency Injection | No          	| Possibly             	| Perhaps, implicit. 	|
| `Async<'T>`  	| Asynchronous local computation 	| No          	| No                   	| Perhaps, explicit. 	|
| `unit -> 'T` 	| Synchronous local computation                   	| No          	| No                   	| No                 	|

**Comment by palladin** [comment]
Btw is it possible to rename `Local<'T>` to `CloudLocal<'T>` (it gives context)? But pls keep the `local {}` builder :)

**Comment by eiriktsarpalis** [comment]
@palladin  :+1:

**Comment by dsyme** [comment]
> In part we were influenced to abandon this principle by the Spark API, in which almost every public method is synchronous.

OK, it sounds like you've made the decision to make all cloud I/O synchronous by default.  That's OK and very simplifying.  

But if so, it really feels like we need to do it for *all* I/O operations including logging and files. For example, see the mix of cloud-monadic and synchronous operations [here](https://github.com/mbraceproject/MBrace.StarterKit/blob/master/HandsOnTutorial/7-using-cloud-data-files.fsx#L17).   And otherwise ``CloudFlow.mapLocal`` is still needed, just to do logging alone.  

It seems this would mean mediating all file and logging operations via an encapsulated primitive:

    ``CloudDirectory.Delete(path)``  --> ``fileSystem.DeleteDirectory(path)``
    ``CloudFile.ReadAllLInes(path)``  --> ``fileSystem.ReadAllLines(path)``
    ``Cloud.Log(msg)``  --> ``log.Log(msg)``
    ``Cloud.Logf(msg)``  --> ``log.Logf(msg)``

Where ``fileSystem`` is approximately ``let fileSystem = cluster.Store.File`` + ``cluster.Store.Directory`` combined. To be honest I quite like this and it feels entirely teachable.  It means an end to all static methods too since they now all need to go via encapsulated objects.

That would leave simpler encapsulated primitives looking like this:

    member queue.Deqeue : unit -> 'T
    member queue.DeqeueAsync : unit -> Async<'T> 

I think the reintroduction of ``async`` here is ok as long as using ``Async`` isn't required in tutorial samples.

I'd be happy to help make this transition if you've really committed to making cloud I/O synchronous by default.

Best regards
don

**Comment by palladin** [comment]
My point was that " for some primitives it is very convenient to have `Async<'T>/'T` methods" and I think it is a mistake to have Spark like sync calls for the majority of the APIs.

**Comment by dsyme** [comment]
After skype chat, the plan of record is:

0. All I/O is done via encapsulated objects with sync+async methods

1. We make a type MBrace.Core.CloudFileSystem that wraps MBrace.Core.Internals.ICloudFIleStore becomes , and is serializable.

2. We get "cluster.FileSystem", scratching ``cluster.Store.File/Path/Directory``

3. We add ``Cloud.GetFileSystem()`` returning ``Local<CloudFileSystem>``

4. ``Cloud.Log/Logf`` keep return type ``Local<unit>``

5. The ``Local`` variations on CloudFlow get removed, replaced by ``CloudFlow.peek : ('T -> Cloud<unit>) -> CloudFlow<T>  -> CloudFlow<T>``

6. ``Local<T>`` gets renamed to ``CloudLocal<T>``

**Comment by eiriktsarpalis** [comment]
I have completed refactoring of all aforementioned points and have added the following features:
  8. Added the module `MBrace.Core.BuilderAsyncExtensions` which allows users to opt-in to direct binding of async workflows in MBrace workflows.
  9. Made changes to the core continuations module that relate to this issue: https://github.com/Microsoft/visualfsharp/issues/686

I'm ready to merge.

**Pull request merged**
