### PR TITLE
possible renamings and documenation around "Local"

### PR DESCRIPTION
**Pull request by dsyme**
RunLocally --> RunOnThisMachine

RunRemote --> RunOnCloud  

Document "Local" more thoroughly in compiler warnings and XML docs.

### CODE REVIEW

**Comment by dsyme** [comment]
I also enlarged the obsolete warnings for ``cloud { ... }`` to push people gently towards ``local { ... }``.  The warnings are long but they do represent a chance to teach the user using consistent, clear explanation.

**Comment by eiriktsarpalis** [comment]
How about `RunAsThreadPoolJob : Cloud<'T> -> 'T` and `AsAsync : Cloud<'T> -> Async<'T>` ? In general I think that the use of 'as' emphasizes the fact that a cloud workflow is being reinterpreted as an async workflow. Compare also with [`Cloud.AsLocal`](https://github.com/mbraceproject/MBrace.Core/blob/master/src/MBrace.Core/Distribution/Combinators.fs#L249), which shoehorns cloud workflows to run with local semantics.

**Comment by dsyme** [comment]
@eiriktsarpalis Do you mean renaming RunOnClient --> RunAsThreadPoolJob and adding a Cloud.AsAsync?  

The first doesn't sound right - it feels like it's important to put "Client" or something to emphasize client execution.  And people might still think that it means the ThreadPools on the cloud workers.

The second feels like it's probably not something we want to encourage (cloud values are for running in the cloud, and if the way to run them locally is through Thespian etc.).

**Comment by dsyme** [comment]
(But the main thing is to remove the use of the word "Locally")

**Comment by eiriktsarpalis** [comment]
I meant them as possible alternative names to the `RunOnClient` and `RunOnClientAsync` methods.

**Comment by eiriktsarpalis** [comment]
@dsyme should I merge this?

**Comment by palladin** [comment]
I think that for consistency reasons we should have RunOnxxx methods like RunOnClient and RunOnCloud.

**Comment by dsyme** [comment]
Looking again I propose we be really explicit about it and use RunOnThisMachine.  Anything else is always open to misinterpretation.

* a naive user may think they can use RunOnClient to schedule work on the client when running in the cluster

* a naïve user may think the "client" is some other thing besides their local machine

Open to suggestions or merge if you think it's the right thing.

**Comment by palladin** [comment]
Oh my.... RunOnThisMachine is so explicit :)

**Comment by eiriktsarpalis** [comment]
Technically speaking, sending jobs to an MBrace cluster running exclusively on my laptop still qualifies as something running on this machine. But besides that, I feel that this name somewhat fails to communicate the fact that the computation will be run with shared memory semantics, in the same address space as the client process.

So not sure about this. How about `RunOnThisProcess` or `RunInProcess` or even `RunInMemory`?

**Comment by eiriktsarpalis** [comment]
Merging this for now, we can revise the naming later on.

**Comment by palladin** [comment]
RunInMemory is a good suggestion.

**Comment by dsyme** [comment]
Re RunInMemory: that will be mis-interpreted too - people will think this means "Run in the cloud, but in-memory in one worker".  Especially in scenarios where "big memory" Azure instances (A11 etc.) are being used.

**Comment by dsyme** [comment]
btw RunOnCurrentMachine may be better than RunOnThisMachine

**Comment by palladin** [comment]
I like more the CurrentMachine suffix maybe because it reminds me .Net apis like CultureInfo.CurrentUICulture, Thread.CurrentThread

**Comment by palladin** [comment]
Or maybe RunOnCurrentProcess to address @eiriktsarpalis's argument.

**Comment by dsyme** [comment]
@palladin Agreed that Current is more aligned with .net terminology.  BTW does it use a new app domain in the current process or the current app domain?

**Comment by eiriktsarpalis** [comment]
@dsyme it uses the current app domain.

**Comment by dsyme** [comment]
Then in principle it should be RunInCurrentDomain.. But many people don't know what "app domains" are these days so it's still open to wild misinterpretation. 

I've changed to RunOnCurrentMachine. RunOnCurrentProcess would also be ok if all other uses of "Process" are systematically removed in favour of "CloudTask" as suggest by @krontogiannis in #121 

A good XML doc comment can also be used to help clarify of course.

**Comment by dsyme** [comment]
I hadn't realized the Run --> RunRemote renaming that preceded this. I think that Run is enough for that one. I'll submit a PR for that

**Pull request merged**
