### PR TITLE
Changes to caching API

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
This PR introduces changes to the caching API in MBrace.Core. It introduces the `ICloudCacheable<'T>` interface:
```fsharp
type ICloudCacheable<'T> =
    abstract UUID : string
    /// Dereference without caching
    abstract GetSourceValue : unit -> Local<'T>
```
which defines an abstract reference to a value. Caching can then be performed using [this](https://github.com/mbraceproject/MBrace.Core/blob/cacheable/src/MBrace.Core/Store/Caching.fs#L56) static API. Both `CloudCell` and `CloudSequence` shed ther caching logic by implementing this interface. 

It is also possible to define ad-hoc cached entities like so:
```fsharp
let cacheable : CloudCacheable<int> = CloudCache.CreateCacheableEntity(local { return fibonacci 5000 })

cacheable.Value : Local<int> // dereferences a cached value
```

### CODE REVIEW

**Comment by eiriktsarpalis** [comment]
@palladin @krontogiannis @isaacabraham @dsyme I'd be interested in your feedback before I merge this.

**Comment by palladin** [comment]
It is somewhat analogous to Lazy<'T> but in a cloud setting. which means that the 
```
local { return fibonacci 5000 }
``` 
can be executed more than once.

**Comment by isaacabraham** [comment]
Looks good! Few small points: -

1. Could we remove the need to wrap the value in a ```local { }``` for ```CreateCachableEntity```?
2. The ```CloudCache``` methods might not need to have the word Cache in every method on it?
3. Will this then be cached across all nodes?

**Comment by eiriktsarpalis** [comment]
@isaacabraham 
1. Should not be difficult to add. My motivation for using `local { }` by default is that I imagine this will be mostly used for IO-bound computation, which is usually established through the mbrace abstractions.
2. Feedback on naming is always important. There are many places in core where it needs to be improved.
3. Depends on the underlying `IObjectCache` implementation. MBrace.Azure currently uses an implementation on top of `System.Runtime.Caching`, which has local-only caching effect. Using Azure caching would probably be different. This ambiguity however is more or less addressed with the `cacheByDefault` parameter.

**Comment by isaacabraham** [comment]
@eiriktsarpalis:

1. Yes, that makes sense - but there might be instances where you have something on your local machine and want to send it to the cluster as well.
3. If you call cache() on a value and want it replicated across all nodes, how would this be achieved?

**Comment by eiriktsarpalis** [comment]
Calling cache() when using `System.Runtime.Caching` will not have any replication effect. This is entirely up to the implementation of the cache. This can be compensated by initializing a cacheable entity with the `cacheByDefault` parameter set to `true`. This enables implicit, on-demand caching in the memory context of any worker that attempts to dereference. In effect it performs lazy replication of the cached value.

**Pull request merged**
